---
helper-operator:
  operators:
    redhat-tekton-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-operators
        create: false
      subscription:
        channel: latest
        approval: Automatic
        operatorName: openshift-pipelines-operator-rh
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true

helper-status-checker:
  enabled: false

  checks:

    - operatorName: openshift-pipelines-operator-rh
      namespace:
        name: openshift-operators
      syncwave: 3

      serviceAccount:
        name: "status-checker-tekton"
