---
helper-operator:
  operators:
    redhat-tekton-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: cicd
        create: true
      subscription:
        channel: latest
        approval: Automatic
        operatorName: openshift-pipelines-operator-rh-latest-redhat-operators-openshift-marketplace
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false

helper-status-checker:
  enabled: false

  checks:

    - operatorName: openshift-pipelines-operator-rh-latest-redhat-operators-openshift-marketplace
      namespace:
        name: cicd
      syncwave: 3

      serviceAccount:
        name: "status-checker-tekton"
